// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 15.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Savory.Continues.Jenkins.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\TheGitlabWorkspace\savory-app\Savory.Continues\Savory.Continues\Jenkins\Template\CSharpLibraryTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class CSharpLibraryTemplate : CSharpLibraryTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("<?xml version=\'1.0\' encoding=\'utf-8\'?>\r\n<project>\r\n  <actions />\r\n  <description>" +
                    "this is a test</description>\r\n  <keepDependencies>false</keepDependencies>\r\n  <p" +
                    "roperties>\r\n");
            
            #line 12 "D:\TheGitlabWorkspace\savory-app\Savory.Continues\Savory.Continues\Jenkins\Template\CSharpLibraryTemplate.tt"

    if (this.Params != null && this.Params.Count > 0)
    {

            
            #line default
            #line hidden
            this.Write("    <hudson.model.ParametersDefinitionProperty>\r\n      <parameterDefinitions>\r\n");
            
            #line 18 "D:\TheGitlabWorkspace\savory-app\Savory.Continues\Savory.Continues\Jenkins\Template\CSharpLibraryTemplate.tt"

        foreach (var param in this.Params)
        {

            
            #line default
            #line hidden
            this.Write("        <hudson.model.StringParameterDefinition>\r\n          <name>");
            
            #line 23 "D:\TheGitlabWorkspace\savory-app\Savory.Continues\Savory.Continues\Jenkins\Template\CSharpLibraryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(param.Key));
            
            #line default
            #line hidden
            this.Write("</name>\r\n          <description>");
            
            #line 24 "D:\TheGitlabWorkspace\savory-app\Savory.Continues\Savory.Continues\Jenkins\Template\CSharpLibraryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(param.Description));
            
            #line default
            #line hidden
            this.Write("</description>\r\n          <defaultValue>");
            
            #line 25 "D:\TheGitlabWorkspace\savory-app\Savory.Continues\Savory.Continues\Jenkins\Template\CSharpLibraryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(param.DefaultValue??string.Empty));
            
            #line default
            #line hidden
            this.Write("</defaultValue>\r\n          <trim>false</trim>\r\n        </hudson.model.StringParam" +
                    "eterDefinition>\r\n");
            
            #line 28 "D:\TheGitlabWorkspace\savory-app\Savory.Continues\Savory.Continues\Jenkins\Template\CSharpLibraryTemplate.tt"

        }

            
            #line default
            #line hidden
            this.Write("      </parameterDefinitions>\r\n    </hudson.model.ParametersDefinitionProperty>\r\n" +
                    "");
            
            #line 33 "D:\TheGitlabWorkspace\savory-app\Savory.Continues\Savory.Continues\Jenkins\Template\CSharpLibraryTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("  </properties>\r\n  <scm class=\"hudson.plugins.git.GitSCM\" plugin=\"git@3.8.0\">\r\n  " +
                    "  <configVersion>2</configVersion>\r\n    <userRemoteConfigs>\r\n      <hudson.plugi" +
                    "ns.git.UserRemoteConfig>\r\n        <url>${Repository}</url>\r\n        <credentials" +
                    "Id>");
            
            #line 42 "D:\TheGitlabWorkspace\savory-app\Savory.Continues\Savory.Continues\Jenkins\Template\CSharpLibraryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GlobalVariables.ScmCredentialsId));
            
            #line default
            #line hidden
            this.Write(@"</credentialsId>
      </hudson.plugins.git.UserRemoteConfig>
    </userRemoteConfigs>
    <branches>
      <hudson.plugins.git.BranchSpec>
        <name>*/${Branch}</name>
      </hudson.plugins.git.BranchSpec>
    </branches>
    <doGenerateSubmoduleConfigurations>false</doGenerateSubmoduleConfigurations>
    <submoduleCfg class=""list"" />
    <extensions />
  </scm>
  <canRoam>true</canRoam>
  <disabled>false</disabled>
  <blockBuildWhenDownstreamBuilding>false</blockBuildWhenDownstreamBuilding>
  <blockBuildWhenUpstreamBuilding>false</blockBuildWhenUpstreamBuilding>
  <triggers />
  <concurrentBuild>false</concurrentBuild>
  <builders>

");
            
            #line 62 "D:\TheGitlabWorkspace\savory-app\Savory.Continues\Savory.Continues\Jenkins\Template\CSharpLibraryTemplate.tt"

    if(this.Cmds != null && this.Cmds.Count > 0)
    {
        foreach(var cmd in this.Cmds)
        {

            
            #line default
            #line hidden
            this.Write("    <hudson.tasks.BatchFile>\r\n      <command>");
            
            #line 69 "D:\TheGitlabWorkspace\savory-app\Savory.Continues\Savory.Continues\Jenkins\Template\CSharpLibraryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cmd));
            
            #line default
            #line hidden
            this.Write("</command>\r\n    </hudson.tasks.BatchFile>\r\n");
            
            #line 71 "D:\TheGitlabWorkspace\savory-app\Savory.Continues\Savory.Continues\Jenkins\Template\CSharpLibraryTemplate.tt"

        }
    }

            
            #line default
            #line hidden
            this.Write("\r\n  </builders>\r\n  <publishers></publishers>\r\n</project>\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class CSharpLibraryTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
